
["block settings"]
	#max height of Japanese Timber Bamboo
	integer = 10
	#Shoji Pane and Shoji are translucent
	"true/false" = false

["item settings"]
	#max Reiryoku amount of Magatama
	capacity = 5600

["entity settings"]
	#increase the player walking spped by 16% so that you can place blocks comfortably
	"true/false" = true

